In [5]:
import pandas as pd
# Đọc file CSV
df = pd.read_csv("salary_survey_raw.csv")
print(f'Shape: {df.shape}')

Shape: (2800, 17)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2800 entries, 0 to 2799
Data columns (total 17 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   timestamp                        2800 non-null   object
 1   how_old_are_you                  2800 non-null   object
 2   industry                         2800 non-null   object
 3   job_title                        2800 non-null   object
 4   additional_context_on_job_title  1831 non-null   object
 5   annual_salary                    2409 non-null   object
 6   additional_monetary_comp         1262 non-null   object
 7   currency                         2800 non-null   object
 8   income_context                   531 non-null    object
 9   country                          2685 non-null   object
 10  us_state                         987 non-null    object
 11  city                             1238 non-null   object
 12  years_of_experience_in_field     2800 non-null   object
 13  years_of_experience_overall      2800 non-null   object
 14  highest_level_of_education       2800 non-null   object
 15  gender                           2731 non-null   object
 16  race                             2034 non-null   object
dtypes: object(17)
memory usage: 372.0+ KB

In [7]:
miss = df.isnull().sum()
pct  = (miss / len(df) * 100).round(1)
report = pd.DataFrame({'count': miss, 'pct_%': pct})
report = report[report['count'] > 0].sort_values('pct_%', ascending=False)
print(report)

                                 count  pct_%
income_context                    2269   81.0
us_state                          1813   64.8
city                              1562   55.8
additional_monetary_comp          1538   54.9
additional_context_on_job_title    969   34.6
race                               766   27.4
annual_salary                      391   14.0
country                            115    4.1
gender                              69    2.5

In [8]:
null_rate = df.isnull().mean().sort_values(ascending=False)
print(null_rate)
#Null hợp lệ là null có ý nghĩa

income_context                     0.810357
us_state                           0.647500
city                               0.557857
additional_monetary_comp           0.549286
additional_context_on_job_title    0.346071
race                               0.273571
annual_salary                      0.139643
country                            0.041071
gender                             0.024643
timestamp                          0.000000
how_old_are_you                    0.000000
industry                           0.000000
job_title                          0.000000
currency                           0.000000
years_of_experience_in_field       0.000000
highest_level_of_education         0.000000
years_of_experience_overall        0.000000
dtype: float64

In [9]:
missing_cols_fill = df.columns[df.isnull().mean() < 0.3]
print(missing_cols_fill)
#Null cần điền  là null thiếu dữ kiệu có thể thay thế được

Index(['timestamp', 'how_old_are_you', 'industry', 'job_title',
       'annual_salary', 'currency', 'country', 'years_of_experience_in_field',
       'years_of_experience_overall', 'highest_level_of_education', 'gender',
       'race'],
      dtype='object')

In [10]:
missing_cols_investigate = df.columns[df.isnull().mean() > 0.5]
print(missing_cols_investigate)
#Null cần xem xét là null bất thường, ảnh hưởng lớn, không nên điền ngay

Index(['additional_monetary_comp', 'income_context', 'us_state', 'city'], dtype='object')

1. Tại sao chúng ta không fillna(mean) cho cột lương?

Không nên fillna(mean) cho cột lương vì:

Salary thường bị lệch và có outlier.

Mean dễ bị kéo lên bởi người lương quá cao.

Fill bằng mean sẽ tạo giá trị không thực tế.

Nên dùng median hoặc median theo từng industry hợp lý hơn.

 2.Xử lý cột 'country' (null = 8%)

In [12]:
import pandas as pd
# Đọc file CSV
df = pd.read_csv("salary_survey_raw.csv")
print(f'Shape: {df.shape}')

Shape: (2800, 17)

In [15]:
country_mode = df['country'].mode()[0]

df['country'] = df['country'].fillna(country_mode)
print(df['country'].isnull().sum())

0

3.Xử lý cột 'years_of_experience' (null = 3%) , có cách nào làm mất ít thông tin hơn?

Có. Vì NULL chỉ khoảng 3% nên thay vì xóa dòng, ta nên fill để giữ dữ liệu.

In [16]:
df['years_of_experience_in_field'].isnull().sum()

np.int64(0)

In [17]:
df[df['years_of_experience_in_field'].isnull()].head()

Empty DataFrame
Columns: [timestamp, how_old_are_you, industry, job_title, additional_context_on_job_title, annual_salary, additional_monetary_comp, currency, income_context, country, us_state, city, years_of_experience_in_field, years_of_experience_overall, highest_level_of_education, gender, race]
Index: []

In [24]:
experience_mode = df['years_of_experience_in_field'].mode()[0]

df['years_of_experience_in_field'] = df['years_of_experience_in_field'].fillna(experience_mode)
print(experience_mode)

11 - 20 years

4.Viết hàm missing_report() ngắn gọn

In [26]:
def missing_report(df):
    return pd.DataFrame({
        'Missing': df.isnull().sum(),
        'Percent': (df.isnull().mean() * 100).round(2)
    })
missing_report(df)

                                 Missing  Percent
timestamp                              0     0.00
how_old_are_you                        0     0.00
industry                               0     0.00
job_title                              0     0.00
additional_context_on_job_title      969    34.61
annual_salary                        391    13.96
additional_monetary_comp            1538    54.93
currency                               0     0.00
income_context                      2269    81.04
country                                0     0.00
us_state                            1813    64.75
city                                1562    55.79
years_of_experience_in_field           0     0.00
years_of_experience_overall            0     0.00
highest_level_of_education             0     0.00
gender                                69     2.46
race                                 766    27.36

1.Missing

In [28]:
import pandas as pd

# Missing report
def missing_report(df):
    return pd.DataFrame({
        'Missing': df.isnull().sum(),
        'Percent': (df.isnull().mean() * 100).round(2)
    })

print(missing_report(df))

                                 Missing  Percent
timestamp                              0     0.00
how_old_are_you                        0     0.00
industry                               0     0.00
job_title                              0     0.00
additional_context_on_job_title      969    34.61
annual_salary                        391    13.96
additional_monetary_comp            1538    54.93
currency                               0     0.00
income_context                      2269    81.04
country                                0     0.00
us_state                            1813    64.75
city                                1562    55.79
years_of_experience_in_field           0     0.00
years_of_experience_overall            0     0.00
highest_level_of_education             0     0.00
gender                                69     2.46
race                                 766    27.36

1.2Handle missing

In [33]:
# salary flag
df['salary_imputed'] = df['annual_salary'].isnull().astype(int)

# convert salary to numeric
df['annual_salary'] = (
    df['annual_salary']
    .astype(str)
    .str.replace(',', '')
)

df['annual_salary'] = pd.to_numeric(df['annual_salary'], errors='coerce')

# fill median theo industry
industry_median = df.groupby('industry')['annual_salary'].transform('median')

df['annual_salary'] = df['annual_salary'].fillna(industry_median)
print(df['annual_salary'].isnull().sum())

0

1.3 Remove Duplicated

In [34]:
print(df.duplicated().sum())

df = df.drop_duplicates()

38

1.4 Fix datatype

In [38]:
# salary về numeric
df = df.copy()
df['annual_salary'] = (
    df['annual_salary']
    .astype(str)
    .str.replace(',', '')
)

df['annual_salary'] = pd.to_numeric(df['annual_salary'], errors='coerce')
print(df['annual_salary'].head())

0     56894.0
1    144543.0
2     52304.0
3     51765.0
4    133218.0
Name: annual_salary, dtype: float64

In [40]:
print(df['annual_salary'].isnull().sum())#null còn không

0

In [39]:
print(df['annual_salary'].dtype)# kiểm tra datatype

float64

2. Decision Log
Quyết định xử lý: Cột 'annual_salary_USD' — missing values

Quan sát: Có nhiều giá trị NULL trong cột lương.

Giả thuyết về nguyên nhân:

Người dùng không muốn khai lương.
Một số dữ liệu bị thiếu khi survey.

Phương án đã xem xét:

Drop hàng NULL
Fill global mean
Fill median theo industry

Quyết định: Phương án 3 + thêm cột salary_imputed

Lý do:

Salary phụ thuộc ngành nghề.
Median ít bị ảnh hưởng bởi outlier hơn mean.
Quyết định xử lý: Cột 'country' — missing 8%

Quan sát: Một phần nhỏ dữ liệu bị thiếu quốc gia.

Giả thuyết về nguyên nhân:

Người tham gia bỏ qua câu hỏi.

Phương án đã xem xét:

Drop rows
Fill mode

Quyết định: Fill bằng mode.

Lý do:

Missing thấp (~8%).
Country là categorical data.
Quyết định xử lý: Duplicate rows

Quan sát: Dataset có duplicated rows.

Giả thuyết về nguyên nhân:

Submit survey nhiều lần.
Lỗi import dữ liệu.

Phương án đã xem xét:

Giữ nguyên
Drop duplicates

Quyết định: Drop duplicates.

Lý do:

Duplicate làm sai kết quả thống kê và visualization.